# LibraryBuildWithAction.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2020-2022  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#
# Before being able to push to my .github\workflows directories,
# I had to create a new personal token with workflow enabled at https://github.com/settings/tokens

# This is the name of the workflow, visible on GitHub UI.
name: LibraryBuildWithAction
on:
  workflow_dispatch: # To run it manually
    description: 'manual build check'
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**LibraryBuildWithAction.yml'
  pull_request:

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} ${{ matrix.log-options }} ${{ matrix.other-options }}

    runs-on: ubuntu-latest # I picked Ubuntu to use shell scripts.

    env:
      # Comma separated list without double quotes around the list.
      REQUIRED_LIBRARIES: # ATtinySerialOut # is loaded as custom library below

    strategy:
      matrix:
        # The matrix will produce one job for each configuration parameter of type `arduino-boards-fqbn`
        # In the Arduino IDE, the fqbn is printed in the first line of the verbose output for compilation as parameter -fqbn=... for the "arduino-builder -dump-prefs" command
        #
        # Examples: arduino:avr:uno, arduino:avr:leonardo, arduino:avr:nano, arduino:avr:mega
        # arduino:sam:arduino_due_x, arduino:samd:arduino_zero_native"
        # ATTinyCore:avr:attinyx5:chip=85,clock=1internal, digistump:avr:digispark-tiny, digistump:avr:digispark-pro
        # STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C8
        # esp8266:esp8266:huzzah:eesz=4M3M,xtal=80, esp32:esp32:featheresp32:FlashFreq=80
        # You may add a suffix behind the fqbn with "|" to specify one board for e.g. different compile options like arduino:avr:uno|trace
        #############################################################################################################
        arduino-boards-fqbn:
          - arduino:avr:uno
#          - digistump:avr:digispark-tiny:clock=clock1
          - ATTinyCore:avr:attinyx5:chip=85,clock=1internal

        # Specify parameters for each board.
        # With sketches-exclude you may exclude specific examples for a board. Use a comma separated list.
        #############################################################################################################
        include:
#          - arduino-boards-fqbn: digistump:avr:digispark-tiny:clock=clock1  # ATtiny85 board @1 MHz
#            platform-url: https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json
#            sketches-exclude: Blink

          - arduino-boards-fqbn: ATTinyCore:avr:attinyx5:chip=85,clock=1internal
            platform-url: https://felias-fogg.github.io/downloads/package_debug_enabled_index.json

        log-options: [-DDEBUG, -DINFO]

        other-options: [-DTEST, -DDUMMY]
#
# build-properties: '{ "All": "-DOPTION_FOR_ALL ${{ matrix.log-options }} ${{ matrix.other-options }}" }'
# Results in 4 jobs -DDEBUG -DTEST, -DDEBUG -DDUMMY, -DINFO -DTEST, -DINFO -DDUMMY


      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout master version of ATtinySerialOut
        uses: actions/checkout@master
        with:
          repository: ArminJo/ATtinySerialOut
          ref: master
          path: CustomLibrary # must contain string "Custom" results in /home/runner/Arduino/libraries/CustomLibrary

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
#          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          platform-url: ${{ matrix.platform-url }}
          sketches-exclude: ${{ matrix.sketches-exclude }}
          build-properties: '{ "All": "-DDUMMY_OPTION_FOR_ALL ${{ matrix.log-options }} ${{ matrix.other-options }}" }'
          # Results in 4 variants -DDEBUG -DTEST, -DDEBUG -DDUMMY, -DINFO -DTEST, -DINFO -DDUMMY e.g. BUILD_PROPERTIES={ "All": "-DDUMMY_OPTION_FOR_ALL -DDEBUG -DTEST" }
          sketch-names:
            WhistleSwitch.ino,
            50Hz.ino,
            SimpleFrequencyDetector.ino
          sketch-names-find-start: examples/*/
          debug-install: true
          debug-compile: true

